repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-ast
  - id: check-illegal-windows-names
  - id: check-json
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: requirements-txt-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
  - id: bandit
    args: ["-ll", "-ii"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
    - id: ruff
      args: [--config, .ruff.toml, --fix]
    - id: ruff-format
      args: [--config, .ruff.toml]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
