name: Fetch Memes (Cronjob)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * **"

jobs:
  fetch-memes:
    name: "Fetch memes daily"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            python-memer

      - name: "Setup Python"
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: "Install Python dependencies"
        run: pip install -r python-memer/requirements.txt

      - name: "Fetch all meme sources"
        run: |
          python python-memer/main.py

      - name: "Commit & push daily memes"
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add -f -A -- memes/

          if git diff --cached --quiet; then
            echo "No changes in memes/"; exit 0
          fi

          git commit -m "Push daily memes [skip ci]" -- memes/

          git pull --rebase origin main
          git push origin HEAD:main
